=== JLGomezEncinar/Validaciones/contacto.dtd
<!ENTITY % datosDir "(calle,cp,ciudad)">
<!ENTITY % datosContacto "(telf,movil,mail)">
<!ELEMENT contacto (nombre,dir,datosCon)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT dir (%datosDir;)>
<!ELEMENT telf (#PCDATA)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT datosCon (%datosContacto;)>

=== JLGomezEncinar/Validaciones/contacto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacto SYSTEM "contacto.dtd">
<contacto>
<nombre></nombre>
<dir>
<calle></calle>
<cp></cp>
<ciudad></ciudad>
</dir>
<datosCon>
<telf></telf>
<movil></movil>
<mail></mail>
</datosCon>
</contacto>
