=== JLGomezEncinar/Validaciones/reparaciones.dtd
<!ENTITY % datosVehiculo "(matricula, marca,modelo)">
<!ENTITY % datosTrabajo "(descripcion, duracion)">
<!ENTITY % datosFactura "(cod,totalAPagar,modoPago)">
<!ELEMENT reparaciones (reparacion)>
<!ELEMENT reparacion (vehiculo,trabajoRealizado,factura)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT vehiculo (%datosVehiculo;)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT trabajoRealizado (%datosTrabajo;)>
<!ELEMENT cod (#PCDATA)>
<!ELEMENT totalAPagar (#PCDATA)>
<!ELEMENT modoPago (#PCDATA)>
<!ELEMENT factura (%datosFactura;)>

=== JLGomezEncinar/Validaciones/reparaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reparaciones SYSTEM "reparaciones.dtd">
<reparaciones>
<reparacion>
<vehiculo>
<matricula></matricula>
<marca></marca>
<modelo></modelo>
</vehiculo>
<trabajoRealizado>
<descripcion></descripcion>
<duracion></duracion>
</trabajoRealizado>
<factura>
<cod></cod>
<totalAPagar></totalAPagar>
<modoPago></modoPago>
</factura>
</reparacion>
</reparaciones>
